### ISSUE TITLE
Walls placed in game are hover the other tiles

### ISSUE THREAD

**Issue by JulienLaclaverie** [JulienLaclaverie/PZ_SpawnObjectsUtil#5]
This issue is making interiors looks verry odd / ugly.

**Comment by SylvainMarty** [comment]
Maybe we could force the program to replace walls before all the others placeholders ?

**Comment by JulienLaclaverie** [comment]
The problem is not with other placeholders, but with in game items like beds, tables, counters, anythig in front of the wall is put behind (more precisely, the wall is placed last so, in front of all the others, placeholders or not)
